name: CI/CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

env:
  PYTHON_VERSION: "3.12"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt pytest ruff httpx

      - name: Auto-fix imports
        run: ruff check --fix .

      - name: Lint
        run: ruff check .

      - name: Test
        env:
          PYTHONPATH: .
        run: pytest -q

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug secrets
        run: |
          echo "Checking required secrets..."
          echo "GCP_WIF_PROVIDER exists: ${{ secrets.GCP_WIF_PROVIDER != '' }}"
          echo "GCP_SA_EMAIL exists: ${{ secrets.GCP_SA_EMAIL != '' }}"
          echo "GCP_PROJECT_ID exists: ${{ secrets.GCP_PROJECT_ID != '' }}"
          echo "GCP_REGION exists: ${{ secrets.GCP_REGION != '' }}"
          echo "GCP_ARTIFACT_REPO exists: ${{ secrets.GCP_ARTIFACT_REPO != '' }}"

      - name: Auth to GCP via OIDC
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 470.0.0"

      - name: Configure Docker auth for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build & Push image
        id: build
        run: |
          IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPO }}/pat-insights:${{ github.sha }}"
          echo "IMAGE=$IMAGE" >> $GITHUB_OUTPUT
          echo "Building image: $IMAGE"
          docker build -t "$IMAGE" .
          echo "Pushing image to Artifact Registry..."
          docker push "$IMAGE"
          echo "Image pushed successfully"

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply (deploy)
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_region: ${{ secrets.GCP_REGION }}
          TF_VAR_image: ${{ steps.build.outputs.IMAGE }}
          TF_VAR_github_owner: ${{ github.repository_owner }}
          TF_VAR_github_repo: ${{ github.event.repository.name }}
        working-directory: terraform
        run: |
          terraform apply -auto-approve \
            -var "project_id=${TF_VAR_project_id}" \
            -var "region=${TF_VAR_region}" \
            -var "image=${TF_VAR_image}" \
            -var "github_owner=${TF_VAR_github_owner}" \
            -var "github_repo=${TF_VAR_github_repo}" \
            -var "ar_repo=${{ secrets.GCP_ARTIFACT_REPO }}"

      - name: Verify deployment
        run: |
          echo "Verifying deployment..."
          if SERVICE_URL=$(gcloud run services describe pat-insights --region=${{ secrets.GCP_REGION }} --format="value(status.url)" 2>/dev/null); then
            echo "✅ Service deployed successfully at: $SERVICE_URL"
          else
            echo "⚠️ Could not retrieve service URL, but deployment may still be successful"
            gcloud run services list --region=${{ secrets.GCP_REGION }}
          fi
